In [1]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import os

In [5]:
path = "data"
os.listdir(path)

['LARD_ADM_SECT_SGG_서울',
 'LARD_ADM_SECT_SGG_서울.zip',
 'LSMD_ADM_SECT_UMD_서울',
 'LSMD_ADM_SECT_UMD_서울.zip',
 '서울시_시군구_5179.gpkg',
 '서울시_읍면동_5179.gpkg',
 '서울시버스정류소위치정보(20240507).csv',
 '서울시버스정류소위치정보(20240507).xlsx',
 '전기차 충전소 설치현황_20240508.csv',
 '전기차 충전소 설치현황_20240508.xls']

In [9]:
df = pd.read_csv("data\서울시버스정류소위치정보(20240507).csv", encoding="CP949")
df

         NODE_ID  ARS_ID           정류소명         X좌표        Y좌표 정류소타입
0      100000001    1001        종로2가사거리  126.987752  37.569806  중앙차로
1      100000002    1002    창경궁.서울대학교병원  126.996521  37.579433  중앙차로
2      100000003    1003      명륜3가.성대입구  126.998251  37.582580  중앙차로
3      100000004    1004       종로2가.삼일교  126.987613  37.568579  중앙차로
4      100000005    1005  혜화동로터리.여운형활동터  127.001744  37.586243  중앙차로
...          ...     ...            ...         ...        ...   ...
11256  124000334   25995          우성아파트  127.139338  37.550386  일반차로
11257  124000333   25996          우성아파트  127.140046  37.550643  일반차로
11258  124000332   25997           조일약국  127.123596  37.533630  일반차로
11259  124000331   25998           성내시장  127.125497  37.536155  일반차로
11260  124000330   25999    천호우체국.로데오거리  127.127337  37.540343  일반차로

[11261 rows x 6 columns]

In [14]:
# csv파일의 좌표를 기준으로 gpd변환
geometry = gpd.points_from_xy(df["X좌표"], df["Y좌표"])
gdf = gpd.GeoDataFrame(df, geometry= geometry, crs=4326)
gdf.head()

,NODE_ID,ARS_ID,정류소명,X좌표,Y좌표,정류소타입,geometry
0,100000001,1001,종로2가사거리,126.987752,37.569806,중앙차로,POINT (126.98775 37.56981)
1,100000002,1002,창경궁.서울대학교병원,126.996521,37.579433,중앙차로,POINT (126.99652 37.57943)
2,100000003,1003,명륜3가.성대입구,126.998251,37.582580,중앙차로,POINT (126.99825 37.58258)
3,100000004,1004,종로2가.삼일교,126.987613,37.568579,중앙차로,POINT (126.98761 37.56858)
4,100000005,1005,혜화동로터리.여운형활동터,127.001744,37.586243,중앙차로,POINT (127.00174 37.58624)

In [15]:
gdf.to_file("data\서울_버스정류소.gpkg", driver="GPKG", encoding="utf-8")